# Generated by Django 2.1.5 on 2019-01-23 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizes', '0009_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='players',
            field=models.ManyToManyField(related_name='quizes', to=settings.AUTH_USER_MODEL),
        ),
    ]
