# Generated by Django 2.1.5 on 2019-01-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0010_quiz_players'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'status']},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['multiplier']},
        ),
    ]
