# Generated by Django 2.1.5 on 2019-01-23 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0011_auto_20190123_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='active_question',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bluff',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bluffs', to='quizes.Answer'),
        ),
    ]
