# Generated by Django 2.1.5 on 2019-01-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0015_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
