# Generated by Django 2.2.4 on 2019-08-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0019_auto_20190718_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[(0, 'Bluff'), (1, 'Guess'), (2, 'Finished')], default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='active_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizes.Question'),
        ),
    ]
