# Generated by Django 2.2.4 on 2019-08-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0020_auto_20190820_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='modus',
            field=models.IntegerField(choices=[(0, 'Bluffing'), (1, 'Guessing')], default=0),
        ),
    ]
