# Generated by Django 2.2.4 on 2020-02-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0021_round_modus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['multiplier', 'id']},
        ),
    ]
