# Generated by Django 3.0.4 on 2020-03-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0023_auto_20200328_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='fobbit',
            name='status',
            field=models.IntegerField(choices=[(0, 'Bluff'), (1, 'Guess'), (2, 'Finished')], default=0),
        ),
    ]
