# Generated by Django 3.0.4 on 2020-03-28 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizes', '0025_auto_20200328_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='players',
        ),
        migrations.AddField(
            model_name='session',
            name='players',
            field=models.ManyToManyField(related_name='quizes_playing', to=settings.AUTH_USER_MODEL),
        ),
    ]
