# Generated by Django 3.0.4 on 2020-06-15 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0026_auto_20200328_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='active_question',
        ),
        migrations.AddField(
            model_name='session',
            name='active_fobbit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in', to='quizes.Fobbit'),
        ),
    ]
