# Generated by Django 3.0.4 on 2020-06-16 16:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizes', '0029_session_modus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bluff',
            unique_together={('fobbit', 'player')},
        ),
    ]
