# Generated by Django 3.0.4 on 2020-06-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0031_auto_20200616_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Round',
        ),
    ]
