# Generated by Django 3.1.7 on 2021-04-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0033_auto_20200617_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fobbit',
            options={'ordering': ['question__order', 'id']},
        ),
    ]
