# Generated by Django 3.1.8 on 2022-02-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0036_session_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fobbit',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='fobbit',
            name='round',
            field=models.IntegerField(default=0),
        ),
    ]
