# Generated by Django 4.2.2 on 2023-06-15 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizes', '0038_session_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('fobbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='quizes.fobbit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fobbit',
            name='players',
            field=models.ManyToManyField(related_name='fobbits', through='quizes.Score', to=settings.AUTH_USER_MODEL),
        ),
    ]
