# Generated by Django 2.1.3 on 2018-12-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_auto_20181220_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
