# Generated by Django 2.1.5 on 2019-01-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0012_auto_20190123_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
    ]
