# Generated by Django 2.1.5 on 2019-01-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0013_auto_20190123_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='showed',
            field=models.BooleanField(default=False),
        ),
    ]
