# Generated by Django 2.2.3 on 2019-07-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0018_auto_20190718_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='active_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quizes.Question'),
        ),
    ]
