# Generated by Django 3.0.4 on 2020-03-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0024_fobbit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fobbit',
            name='quiz',
        ),
        migrations.AddField(
            model_name='fobbit',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fobbits', to='quizes.Session'),
            preserve_default=False,
        ),
    ]
