# Generated by Django 3.1.7 on 2021-04-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0034_auto_20210415_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='url',
            new_name='image_url',
        ),
    ]
