# Generated by Django 4.1.3 on 2022-12-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0037_auto_20220219_1902"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
