# Generated by Django 4.2.8 on 2024-07-23 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizes', '0039_score_fobbit_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeAnswers', to='quizes.answer')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeAnswers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
