#!/usr/bin/env bash

set -e

update=false
while [ $# -gt 0 ]; do
    case "$1" in
        --update)
            update=true
        ;;
    esac
	shift
done

cd "$(dirname "$0")/.."

if $update ; then
    scripts/update
fi

if [[ $(uname -s) == Linux ]];then
    hostnames=$(hostname -I)
    hostnames=${hostnames//[' ']/,}
    export HOSTNAMES=$hostnames
elif [[ $(uname -s) == Darwin ]];then
    hostnames=$(ipconfig getifaddr en0)
    export HOSTNAMES=$hostnames
fi

pipenv run daphne fobbage.asgi:application
