#!/usr/bin/env bash

set -e

interactive=true
while [ $# -gt 0 ]; do
  	case "$1" in
    	--no-input)
    	  	interactive=false
      	;;
  	esac
	shift
done

if $interactive ; then
    echo "WARNING!! This script REMOVE your LOCAL fobbage database and you LOSE all the data."
    read -p "Are you sure you want to delete all data? (y/N): " -n 1 -r
    echo    # (optional) move to a new line
    if [[ ! $REPLY =~ ^[Yy]$ ]] ; then
        exit 1
    fi
fi

cd "$(dirname "$0")/.."

scripts/bootstrap

if [ -f ./test.db ]; then
    rm ./test.db
else
    echo "==> Removing fobbage DB"
    dropdb fobbage
    echo "==> Re-create fobbage DB"
    createdb fobbage
fi

echo "==> Migrating DB"
poetry run python ./manage.py migrate

echo "==> Loading initial data"
poetry run python ./manage.py load_initial_data

echo "==> Setting up git hooks"
git config core.hooksPath .git-hooks

echo "==> App is now ready to go!"
