#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

scripts/bootstrap

echo "==> Updating db…"
# run all database migrations to ensure everything is up to date.
poetry run python ./manage.py migrate
